name: build-env

channels:
  - conda-forge

dependencies:
  - python=3.12
  - pip
  - jupyter_server
  - notebook>=7.5
  - jupyterlite-core>=0.7
  - jupyterlite-pyodide-kernel
  - jupyterlite-xeus>=4.3
